import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  splash: { flex: 1, alignItems: "center", justifyContent: "center" },
  screen: { flex: 1 },
  header: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  heading: { fontSize: 28, fontWeight: "800", letterSpacing: -0.7 },
  subtitle: { fontSize: 14, marginTop: 3 },
  headerLogo: { width: 48, height: 48, borderRadius: 14 },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  searchBar: {
    marginHorizontal: 16,
    marginBottom: 20,
    minHeight: 50,
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
  },
  section: { marginTop: 30 },
  sectionTitle: { fontSize: 18, fontWeight: "800", marginBottom: 12 },
  homeSectionTitle: { marginHorizontal: 16 },
  horizontalList: { paddingHorizontal: 16, gap: 12 },
  carouselDots: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 6,
    marginTop: 12,
  },
  carouselDot: { width: 7, height: 7, borderRadius: 4 },
  chips: { flexDirection: "row", flexWrap: "wrap", gap: 9, paddingVertical: 8 },
  homeCategoryList: {
    flexWrap: "nowrap",
    paddingHorizontal: 16,
    paddingBottom: 4,
  },
  viewAllCategory: {
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  chip: { paddingHorizontal: 14, paddingVertical: 9, borderRadius: 999 },
  auth: { flex: 1, justifyContent: "center", padding: 24, gap: 16 },
  logo: {
    width: 62,
    height: 62,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
  },
  logoImage: { width: 76, height: 76, borderRadius: 22, alignSelf: "center" },
  authTitle: { fontSize: 28, fontWeight: "800", textAlign: "center" },
  authSubtitle: { textAlign: "center", lineHeight: 21, marginBottom: 8 },
  link: { textAlign: "center", fontWeight: "700", padding: 4 },
  authSheetOverlay: { flex: 1, justifyContent: "flex-end" },
  authSheetBackdrop: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  authSheetKeyboard: { justifyContent: "flex-end" },
  authSheet: {
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 22,
    paddingTop: 10,
    paddingBottom: 12,
    gap: 14,
  },
  authSheetHandle: {
    width: 42,
    height: 5,
    borderRadius: 3,
    alignSelf: "center",
    marginBottom: 4,
  },
  authSheetHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 14,
  },
  authSheetTitle: { fontSize: 24, fontWeight: "800" },
  authSheetSubtitle: { fontSize: 13, lineHeight: 19, marginTop: 4 },
  form: { padding: 20, gap: 18 },
  hero: { width: "100%", aspectRatio: 0.84, backgroundColor: "#D8D5DF" },
  heroImage: { width: "100%", height: "100%" },
  expandImageButton: {
    position: "absolute",
    right: 16,
    bottom: 16,
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0, 0, 0, 0.55)",
  },
  detailBody: { padding: 20, gap: 18 },
  titleRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  detailTitle: { fontSize: 24, fontWeight: "800" },
  stats: { flexDirection: "row", gap: 20 },
  promptPage: { padding: 18, gap: 16 },
  promptCard: { padding: 18, borderWidth: 1, borderRadius: 18, gap: 12 },
  profileGuest: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 28,
    gap: 15,
  },
  googleSignInButton: {
    width: "100%",
    maxWidth: 340,
    minHeight: 54,
    borderWidth: 1,
    borderRadius: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    paddingHorizontal: 18,
  },
  googleSignInText: { fontSize: 15, fontWeight: "700" },
  googlePromptDescription: {
    maxWidth: 360,
    textAlign: "center",
    lineHeight: 20,
  },
  avatar: {
    width: 88,
    height: 88,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: { color: "#FFF", fontSize: 34, fontWeight: "800" },
  profileTop: { alignItems: "center", padding: 24, gap: 7 },
  menu: { margin: 16, borderRadius: 20, paddingHorizontal: 14 },
  menuRow: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  segment: { flexDirection: "row", gap: 8 },
  segmentItem: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  settingRow: {
    padding: 16,
    borderRadius: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  legal: { padding: 22, gap: 18 },
});
