import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  splash: { flex: 1, alignItems: "center", justifyContent: "center" },
  screen: { flex: 1 },
  ambientScreen: { flex: 1, overflow: "hidden" },
  ambientBackground: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    overflow: "hidden",
  },
  ambientBackgroundImage: {
    position: "absolute",
    top: -30,
    right: -30,
    bottom: -30,
    left: -30,
    opacity: 0.42,
  },
  ambientBackgroundOverlay: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  header: {
    paddingHorizontal: 18,
    paddingTop: 14,
    paddingBottom: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  heading: { fontSize: 29, fontWeight: "900", letterSpacing: -0.9 },
  subtitle: { fontSize: 14, marginTop: 4, lineHeight: 19 },
  headerLogo: { width: 50, height: 50, borderRadius: 17 },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  searchBar: {
    marginHorizontal: 18,
    marginBottom: 10,
    minHeight: 54,
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
  },
  section: { marginTop: 28 },
  sectionTitle: {
    fontSize: 19,
    fontWeight: "900",
    letterSpacing: -0.35,
    marginBottom: 13,
  },
  homeSectionTitle: { marginHorizontal: 18 },
  horizontalList: { paddingHorizontal: 18, gap: 14 },
  carouselDots: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 6,
    marginTop: 12,
  },
  carouselDot: { width: 7, height: 7, borderRadius: 4 },
  chips: { flexDirection: "row", flexWrap: "wrap", gap: 9, paddingVertical: 8 },
  homeCategoryList: {
    flexWrap: "nowrap",
    paddingHorizontal: 16,
    paddingBottom: 4,
  },
  viewAllCategory: {
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  chip: { paddingHorizontal: 14, paddingVertical: 9, borderRadius: 999 },
  auth: { flex: 1, justifyContent: "center", padding: 24, gap: 16 },
  logo: {
    width: 62,
    height: 62,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
  },
  logoImage: { width: 76, height: 76, borderRadius: 22, alignSelf: "center" },
  authTitle: { fontSize: 28, fontWeight: "800", textAlign: "center" },
  authSubtitle: { textAlign: "center", lineHeight: 21, marginBottom: 8 },
  link: { textAlign: "center", fontWeight: "700", padding: 4 },
  authSheetOverlay: { flex: 1, justifyContent: "flex-end" },
  authSheetBackdrop: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  authSheetKeyboard: { justifyContent: "flex-end" },
  authSheet: {
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 22,
    paddingTop: 10,
    paddingBottom: 12,
    gap: 14,
  },
  authSheetHandle: {
    width: 42,
    height: 5,
    borderRadius: 3,
    alignSelf: "center",
    marginBottom: 4,
  },
  authSheetHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 14,
  },
  authSheetTitle: { fontSize: 24, fontWeight: "800" },
  authSheetSubtitle: { fontSize: 13, lineHeight: 19, marginTop: 4 },
  form: { padding: 20, gap: 18 },
  hero: { width: "100%", aspectRatio: 0.84, backgroundColor: "#D8D5DF" },
  heroImage: { width: "100%", height: "100%" },
  expandImageButton: {
    position: "absolute",
    right: 16,
    bottom: 16,
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0, 0, 0, 0.55)",
  },
  detailBody: { padding: 20, gap: 18 },
  titleRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  detailTitle: { fontSize: 24, fontWeight: "800" },
  stats: { flexDirection: "row", gap: 20 },
  promptPage: { padding: 18, gap: 16 },
  promptCard: { padding: 18, borderWidth: 1, borderRadius: 18, gap: 12 },
  profileGuest: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 28,
    gap: 15,
  },
  googleSignInButton: {
    width: "100%",
    maxWidth: 340,
    minHeight: 54,
    borderWidth: 1,
    borderRadius: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    paddingHorizontal: 18,
  },
  googleSignInText: { fontSize: 15, fontWeight: "700" },
  googlePromptDescription: {
    maxWidth: 360,
    textAlign: "center",
    lineHeight: 20,
  },
  avatar: {
    width: 96,
    height: 96,
    borderRadius: 48,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: { color: "#FFF", fontSize: 36, fontWeight: "900" },
  avatarRing: {
    padding: 4,
    borderWidth: 1,
    borderRadius: 54,
    marginBottom: 5,
  },
  profileTop: {
    alignItems: "center",
    marginHorizontal: 16,
    paddingHorizontal: 22,
    paddingVertical: 28,
    borderWidth: 1,
    borderRadius: 28,
    gap: 7,
  },
  profileBadge: {
    marginTop: 7,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  menu: {
    margin: 16,
    borderWidth: 1,
    borderRadius: 24,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  menuRow: {
    minHeight: 64,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  menuIcon: {
    width: 38,
    height: 38,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  segment: { flexDirection: "row", gap: 8 },
  segmentItem: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  settingRow: {
    padding: 16,
    borderRadius: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  legal: { padding: 22, gap: 18 },
});
